### ISSUE TITLE
JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by Teenie-weenie** [twitter/recess#165]
i tried to compile LESS file to CSS using node.js, grunt and recess. But I've got an error **JS Allocation failed - process out of memory** when I tried to compile less file with new flexbox css properties
```less
.flexbox {	
	&-vertical {	
		-webkit-box-orient: vertical;
		-moz-box-orient: vertical;
		-ms-flex-direction: column;	
		-webkit-flex-direction: column;			
		flex-direction:column;		
		align-items: center;
	}
}
```

but less file was compiled correctly when I removed part of properties like

```less
.flexbox {	
	&-vertical {	
		-webkit-box-orient: vertical;
		-moz-box-orient: vertical;
	}
}
```
I use Node.js 0.10.28 (x64) and the latest recess version.
